-- MySQL Script generated by MySQL Workbench
-- Tue Aug 24 02:23:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Acionistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Acionistas` (
  `CNPJ` INT NOT NULL,
  `Nome` VARCHAR(100) NULL,
  `Corretora` VARCHAR(45) NULL,
  PRIMARY KEY (`CNPJ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funçoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funçoes` (
  `ID_TRAN` INT NOT NULL,
  `Quantidade` INT NULL,
  `Data` INT NULL,
  PRIMARY KEY (`ID_TRAN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Financiamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Financiamento` (
  `ID_F` INT NOT NULL,
  `Juros` INT NULL,
  `Garantia` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_F`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cartão`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cartão` (
  `ID_Card` INT NOT NULL,
  `Bandeira` VARCHAR(45) NULL,
  `CVV` INT NULL,
  PRIMARY KEY (`ID_Card`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `CPF` INT NOT NULL,
  `Nome` VARCHAR(100) NULL,
  `Endereço` VARCHAR(45) NULL,
  `Financiamento_ID_F` INT NOT NULL,
  PRIMARY KEY (`CPF`, `Financiamento_ID_F`),
  INDEX `fk_Cliente_Financiamento1_idx` (`Financiamento_ID_F` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Financiamento1`
    FOREIGN KEY (`Financiamento_ID_F`)
    REFERENCES `mydb`.`Financiamento` (`ID_F`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Conta` (
  `Conta` INT NOT NULL,
  `Agencia` INT NOT NULL,
  `Banco` VARCHAR(20) NULL,
  `Cartão_ID_Card` INT NOT NULL,
  `Cartão_ID_Card1` INT NOT NULL,
  `Cliente_CPF` INT NOT NULL,
  PRIMARY KEY (`Conta`, `Agencia`, `Cartão_ID_Card`, `Cartão_ID_Card1`, `Cliente_CPF`),
  INDEX `fk_Conta_Cartão1_idx` (`Cartão_ID_Card1` ASC) VISIBLE,
  INDEX `fk_Conta_Cliente1_idx` (`Cliente_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Conta_Cartão1`
    FOREIGN KEY (`Cartão_ID_Card1`)
    REFERENCES `mydb`.`Cartão` (`ID_Card`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Conta_Cliente1`
    FOREIGN KEY (`Cliente_CPF`)
    REFERENCES `mydb`.`Cliente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seguro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seguro` (
  `ID_S` INT NOT NULL,
  `Preço` INT NULL,
  `Plano` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_S`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamentos` (
  `ID_D` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Orçamento` INT NULL,
  PRIMARY KEY (`ID_D`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gerente` (
  `CPF` INT NOT NULL,
  `Nome` VARCHAR(100) NULL,
  `Telefone` INT NULL,
  `Departamentos_ID_D` INT NOT NULL,
  `Conta_Conta` INT NOT NULL,
  `Conta_Agencia` INT NOT NULL,
  `Conta_Cartão_ID_Card` INT NOT NULL,
  PRIMARY KEY (`CPF`, `Departamentos_ID_D`, `Conta_Conta`, `Conta_Agencia`, `Conta_Cartão_ID_Card`),
  INDEX `fk_Gerente_Departamentos1_idx` (`Departamentos_ID_D` ASC) VISIBLE,
  INDEX `fk_Gerente_Conta1_idx` (`Conta_Conta` ASC, `Conta_Agencia` ASC, `Conta_Cartão_ID_Card` ASC) VISIBLE,
  CONSTRAINT `fk_Gerente_Departamentos1`
    FOREIGN KEY (`Departamentos_ID_D`)
    REFERENCES `mydb`.`Departamentos` (`ID_D`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gerente_Conta1`
    FOREIGN KEY (`Conta_Conta` , `Conta_Agencia` , `Conta_Cartão_ID_Card`)
    REFERENCES `mydb`.`Conta` (`Conta` , `Agencia` , `Cartão_ID_Card`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Caixa Eletronico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Caixa Eletronico` (
  `ID_CE` INT NOT NULL,
  `Endereço` VARCHAR(45) NULL,
  `Banco` VARCHAR(20) NULL,
  `Funçoes_ID_TRAN` INT NOT NULL,
  PRIMARY KEY (`ID_CE`, `Funçoes_ID_TRAN`),
  INDEX `fk_Caixa Eletronico_Funçoes1_idx` (`Funçoes_ID_TRAN` ASC) VISIBLE,
  CONSTRAINT `fk_Caixa Eletronico_Funçoes1`
    FOREIGN KEY (`Funçoes_ID_TRAN`)
    REFERENCES `mydb`.`Funçoes` (`ID_TRAN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Banco` (
  `CNPJ` INT NOT NULL,
  `Nome` VARCHAR(100) NULL,
  `Endereço` VARCHAR(100) NULL,
  `Seguro_ID_S` INT NOT NULL,
  `Financiamento_ID_F` INT NOT NULL,
  `Caixa Eletronico_ID_CE` INT NOT NULL,
  `Departamentos_ID_D` INT NOT NULL,
  PRIMARY KEY (`CNPJ`, `Seguro_ID_S`, `Financiamento_ID_F`, `Caixa Eletronico_ID_CE`, `Departamentos_ID_D`),
  INDEX `fk_Banco_Seguro1_idx` (`Seguro_ID_S` ASC) VISIBLE,
  INDEX `fk_Banco_Financiamento1_idx` (`Financiamento_ID_F` ASC) VISIBLE,
  INDEX `fk_Banco_Caixa Eletronico1_idx` (`Caixa Eletronico_ID_CE` ASC) VISIBLE,
  INDEX `fk_Banco_Departamentos1_idx` (`Departamentos_ID_D` ASC) VISIBLE,
  CONSTRAINT `fk_Banco_Seguro1`
    FOREIGN KEY (`Seguro_ID_S`)
    REFERENCES `mydb`.`Seguro` (`ID_S`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Banco_Financiamento1`
    FOREIGN KEY (`Financiamento_ID_F`)
    REFERENCES `mydb`.`Financiamento` (`ID_F`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Banco_Caixa Eletronico1`
    FOREIGN KEY (`Caixa Eletronico_ID_CE`)
    REFERENCES `mydb`.`Caixa Eletronico` (`ID_CE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Banco_Departamentos1`
    FOREIGN KEY (`Departamentos_ID_D`)
    REFERENCES `mydb`.`Departamentos` (`ID_D`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Acionistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Acionistas` (
  `CNPJ` INT NOT NULL,
  `Nome` VARCHAR(100) NULL,
  `Corretora` VARCHAR(45) NULL,
  PRIMARY KEY (`CNPJ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tem` (
  `Banco_CNPJ` INT NOT NULL,
  `Acionistas_CNPJ` INT NOT NULL,
  PRIMARY KEY (`Banco_CNPJ`, `Acionistas_CNPJ`),
  INDEX `fk_Banco_has_Acionistas_Acionistas1_idx` (`Acionistas_CNPJ` ASC) VISIBLE,
  INDEX `fk_Banco_has_Acionistas_Banco_idx` (`Banco_CNPJ` ASC) VISIBLE,
  CONSTRAINT `fk_Banco_has_Acionistas_Banco`
    FOREIGN KEY (`Banco_CNPJ`)
    REFERENCES `mydb`.`Banco` (`CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Banco_has_Acionistas_Acionistas1`
    FOREIGN KEY (`Acionistas_CNPJ`)
    REFERENCES `mydb`.`Acionistas` (`CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente_has_Seguro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente_has_Seguro` (
  `Cliente_CPF` INT NOT NULL,
  `Seguro_ID_S` INT NOT NULL,
  PRIMARY KEY (`Cliente_CPF`, `Seguro_ID_S`),
  INDEX `fk_Cliente_has_Seguro_Seguro1_idx` (`Seguro_ID_S` ASC) VISIBLE,
  INDEX `fk_Cliente_has_Seguro_Cliente1_idx` (`Cliente_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_has_Seguro_Cliente1`
    FOREIGN KEY (`Cliente_CPF`)
    REFERENCES `mydb`.`Cliente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Seguro_Seguro1`
    FOREIGN KEY (`Seguro_ID_S`)
    REFERENCES `mydb`.`Seguro` (`ID_S`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
